sudo : required
services:
    - docker

before_install : 
    - docker build -t naveenselvaraj93/multi-docker -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true naveenselvaraj93/multi-docker npm run test

language: generic    

after_sucess:
    - docker build -t sundarsingh19/multi-client-n ./client
    - docker build -t sundarsingh19/multi-nginx-n ./nginx
    - docker build -t sundarsingh19/multi-server-n ./server
    - docker build -t sundarsingh19/multi-worker-n ./worker

    #Login to the docker CLI

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #take those images and push them to docker hub

    - docker push sundarsingh19/multi-client-n
    - docker push sundarsingh19/multi-nginx-n
    - docker push sundarsingh19/multi-server-n
    - docker push sundarsingh19/multi-worker-n



# delpoy:
#     provider: elasticbeanstalk
#     region: "ap-south-1"
#     app: "docker-react"
#     env: "DockerReact-env"
#     bucket_name: "elasticbeanstalk-ap-south-1-051675516925"
#     bucket_path: "docker-react"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY    