sudo : required
services:
    - docker

before_install : 
    - docker build -t naveenselvaraj93/multi-docker -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true naveenselvaraj93/multi-docker npm run test

language: generic    

after_sucess:
    - docker build -t naveenselvaraj/multi-client ./client
    - docker build -t naveenselvaraj/multi-nginx ./nginx
    - docker build -t naveenselvaraj/multi-server ./server
    - docker build -t naveenselvaraj/multi-worker ./worker

    #Login to the docker CLI

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #take those images and push them to docker hub

    - docker push naveenselvaraj/multi-client
    - docker push naveenselvaraj/multi-nginx
    - docker push naveenselvaraj/multi-server
    - docker push naveenselvaraj/multi-worker



delpoy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-051675516925"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    